// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLRQMHYGf3S_HXB6O_ZS3f0wNMqXlgLlY',
    appId: '1:789302286158:web:d1a973bc72e7c98618b01f',
    messagingSenderId: '789302286158',
    projectId: 'anonymousfoodie-c1074',
    authDomain: 'anonymousfoodie-c1074.firebaseapp.com',
    storageBucket: 'anonymousfoodie-c1074.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkz0fg6Qf6MZKfgoXVAQ0SUMQrk4CLw-4',
    appId: '1:789302286158:android:8cba40b3a5cf858218b01f',
    messagingSenderId: '789302286158',
    projectId: 'anonymousfoodie-c1074',
    storageBucket: 'anonymousfoodie-c1074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHBtCT6vebwKfOFThf2Dpl0Ik1151mFnQ',
    appId: '1:789302286158:ios:ec9118eee6a7c70f18b01f',
    messagingSenderId: '789302286158',
    projectId: 'anonymousfoodie-c1074',
    storageBucket: 'anonymousfoodie-c1074.appspot.com',
    iosBundleId: 'com.example.anonymousFoodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHBtCT6vebwKfOFThf2Dpl0Ik1151mFnQ',
    appId: '1:789302286158:ios:c19885456291f50818b01f',
    messagingSenderId: '789302286158',
    projectId: 'anonymousfoodie-c1074',
    storageBucket: 'anonymousfoodie-c1074.appspot.com',
    iosBundleId: 'com.example.anonymousFoodie.RunnerTests',
  );
}
